### ISSUE TITLE
Make MemoryBuffer (to expose functionalities of ThriftStructReader/ThriftStructWriter) public

### ISSUE THREAD

**Issue by Tuatan** [SolalPirelli/ThriftSharp#3]
Hello @SolalPirelli ,

Any reason why you decided not to expose the _ThriftStructReader_/_ThriftStructWriter_ (or just _MemoryBuffer_)? It seems like those two are really useful to have to dump the communication messages.

**Comment by SolalPirelli** [comment]
If I understand correctly, you wish to convert Thrift objects to and from their encoded representation, without actually calling methods?

Would this kind of API be enough?

```
static class ThriftSerializer
{
    static byte[] Serialize<T>(T obj);
    static T Deserialize<T>(byte[] bytes);
}
```

Do you also need to convert pseudo-objects like method calls (which do not have equivalent, manually written classes) ?

**Comment by Tuatan** [comment]
Yes, @SolalPirelli, that is something I would like to see here, so that library could be used for serialization/deserialization purposes. That API completely satisfies the needs.

**Comment by SolalPirelli** [comment]
OK, that should be fairly easy to do.

Unless you need it urgently, I'll wait for .NET Core/Standard 2.0 to RTM (which is pretty soon, apparently) as the current project structure is still project.json-based and extremely brittle (result of my "clever" decision to write unit tests in F#...).

**Comment by SolalPirelli** [comment]
As promised, .NET Standard 2.0 is out so ThriftSharp 6.0.1 is out (6.0.0 was me forgetting the rd.xml file). It adds a `ThriftSerializer` with the above API, as well as a `ThriftMemoryTransport` in case that's useful since that's what the serializer uses under the covers.

Note that I haven't really tested it outside of unit tests, please do open issues if something weird comes up (with System.Linq.Expressions that happens sometimes, e.g. the interpreter built into UWP is randomly missing some methods...).

**Comment by SolalPirelli** [comment]
Closing since this is done - feel free to reopen if needed.
